version: "3.6"
services:
  coincap_redpanda:
    extends:
      file: ./Redpanda/docker-compose.yaml
      service: coincap_redpanda
  coincap_redpanda_console:
    extends:
      file: ./Redpanda/docker-compose.yaml
      service: coincap_redpanda_console
  coincap_producer:
    build:
      context: ./CoincapProducer
      dockerfile: Dockerfile
    container_name: coincap_producer
    environment:
      REDPANDA_BROKERS: "coincap_redpanda:29092"
      ASSET_PRICES_TOPIC: "$ASSET_PRICES_TOPIC"
