version: "3.6"
services:
  coincap-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coincap-producer
    environment:
      REDPANDA_BROKERS: "coincap-redpanda:29092"
      ASSET_PRICES_TOPIC: "data.asset_prices"
    depends_on:
      coincap-redpanda:
        condition: service_healthy