version: "3.6"
services:
  coincap-consumer:
    build:
      context: .
      dockerfile: SparkMaster.DockerFile
    container_name: coincap-consumer
    ports:
      - "9090:8080"
      - "7014:7077"
      - "4010:4040"

  coincap-consumer-worker-1:
    build:
      context: .
      dockerfile: SparkWorker.DockerFile
    container_name: coincap-consumer-worker-1
    ports:
      - 8041:8081
    depends_on:
      - coincap-consumer
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://coincap-consumer:7077

  coincap-consumer-worker-2:
    build:
      context: .
      dockerfile: SparkWorker.DockerFile
    container_name: coincap-consumer-worker-2
    ports:
      - 8042:8081
    depends_on:
      - coincap-consumer
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://coincap-consumer:7077
